-- creation table: ChaineHotel
CREATE TABLE IF NOT EXISTS ChaineHotel (
	chaine_ID INTEGER NOT NULL UNIQUE,  
    	nom_chaine VARCHAR(255),
	rue VARCHAR(255),
	ville VARCHAR(255),
	code_postal VARCHAR(6),
	nombre_hotel INTEGER,
	courriel_chaine VARCHAR(255),
	numero_telephone_chaine VARCHAR(10),
	PRIMARY KEY (chaine_ID)
);

-- creation table: Hotel
CREATE TABLE IF NOT EXISTS Hotel (
	hotel_ID INTEGER NOT NULL UNIQUE,  
   	nom_hotel VARCHAR(255),
	rue VARCHAR(255),
	ville VARCHAR(255),
	code_postal VARCHAR(6),
	nombre_chambre INTEGER,
	courriel_hotel VARCHAR(255),
	numero_telephone_hotel VARCHAR(10),
	etoile INTEGER,
	chaine_ID INTEGER,
	PRIMARY KEY (hotel_ID),
	FOREIGN KEY(chaine_ID) REFERENCES chaineHotel(chaine_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- creation table: Chambre
CREATE TABLE IF NOT EXISTS Chambre (
	chambre_ID INTEGER NOT NULL UNIQUE,
	prix INTEGER,
    	commodite VARCHAR(255),
	capacite VARCHAR(255),
	extensible VARCHAR(255),
	dommage VARCHAR(255),
	vue VARCHAR(255),
	hotel_ID INTEGER,
	PRIMARY KEY (chambre_ID),
	FOREIGN KEY(hotel_ID) REFERENCES hotel(hotel_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- creation table: Employe
CREATE TABLE IF NOT EXISTS Employe (
	NAS_employe INTEGER NOT NULL UNIQUE,
	nom_employe VARCHAR(255),
	prenom_employe VARCHAR(255),
	rue VARCHAR(255),
	ville VARCHAR(255),
	code_postal VARCHAR(6),
	role VARCHAR(255),
	courriel_employee VARCHAR(255),
	motpasse_employee VARCHAR(255),
	hotel_ID INTEGER,
	PRIMARY KEY (NAS_employe),
	FOREIGN KEY (hotel_ID) REFERENCES Hotel(hotel_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- creation table: Client
CREATE TABLE IF NOT EXISTS Client (
	NAS_client INTEGER NOT NULL UNIQUE,
	nom_client VARCHAR(255),
	prenom_client VARCHAR(255),
	rue VARCHAR(255),
	ville VARCHAR(255),
	code_postal VARCHAR(6),
	courriel_client VARCHAR(255),
	motpasse_client VARCHAR(255),
	date_enregistrement DATE,
	PRIMARY KEY (NAS_client)
);

-- creation table: Reservation
CREATE TABLE IF NOT EXISTS Reservation (
	reservation_ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10000 INCREMENT BY 1),
	debut_date_reservation DATE,
	fin_date_reservation DATE,
	NAS_client INTEGER,
	chambre_ID INTEGER,
	PRIMARY KEY (reservation_ID),
	FOREIGN KEY (NAS_client) REFERENCES Client(NAS_client) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (chambre_ID) REFERENCES Chambre(chambre_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- creation table: Location
CREATE TABLE IF NOT EXISTS Location ( 
	location_ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 50000 INCREMENT BY 1),
	debut_date_location DATE,
	fin_date_location DATE,
	montant INTEGER,
	transaction_date DATE,
	NAS_employe INTEGER,
	NAS_client INTEGER,
	chambre_ID INTEGER,
	reservation_ID INTEGER,
	PRIMARY KEY (location_ID),
	FOREIGN KEY (NAS_employe) REFERENCES Employe(NAS_employe) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (NAS_client) REFERENCES Client(NAS_client) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (chambre_ID) REFERENCES Chambre(chambre_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (reservation_ID) REFERENCES Reservation(reservation_ID),
);
