--Pour tester la page manageChambre
-- Insérer des clients
INSERT INTO Client (NAS_client, nom_client, prenom_client, rue, ville, code_postal, courriel_client, motpasse_client, date_enregistrement)
VALUES 
    (100000006, 'Moreau', 'Luc', '321 Boulevard Sud', 'Montréal', 'H3Z2Y7', 'luc.moreau@email.com', 'mdp123', '2025-03-12'),
    (100000007, 'Bertrand', 'Elise', '789 Rue Ouest', 'Québec', 'G1T4X6', 'elise.bertrand@email.com', 'pass456', '2025-03-13');
INSERT INTO Chambre (chambre_ID, prix, commodite, capacite, extensible, dommage, vue, hotel_ID)
VALUES
(218, 150, 'TV + fridge', 'simple', 'non', 'oui', 'montagne', 21),
(219, 200, 'TV + fridge', 'double', 'non', 'oui', 'montagne', 21),
(220, 225, 'TV + fridge + sofa', 'double', 'oui', 'non', 'mer', 21),
(221, 300, 'TV + fridge', 'famille', 'non', 'non', 'mer', 21),
-- Insérer les réservations
INSERT INTO Reservation (debut_date_reservation, fin_date_reservation, NAS_client, chambre_ID)
VALUES 
    ('2025-03-18', '2025-04-10', 100000006, 221),
    ('2025-04-05', '2025-04-15', 100000007, 218);
--Verifier les id des reservations qui est generer automatiquement en utilisant GENERATED BY DEFAULT AS IDENTITY (START WITH 50000 INCREMENT BY 1) 
--Inserer les locations
INSERT INTO Location (debut_date_location, fin_date_location, NAS_client, chambre_ID, NAS_employe)
VALUES 
    ('2025-03-18', '2025-03-25', 100000005, 218, 210000001),
    ('2025-03-20', '2025-03-27', 100000004, 219, 210000001);

